{
 "title": "ZoneMinder",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "MonitorName",
    "label": "Monitor Name",
    "query": {
     "query": "label_values(zm_monitor_info,name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Daemon Check",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "zm_daemon_check" }
   ]
  },
  {
   "title": "ZMES Websocket Response Time",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "zm_zmes_websocket_response_time_seconds{status=\"Success\"}"
    }
   ]
  },
  {
   "title": "Exporter Query Time",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "zm_query_time_seconds" }
   ]
  },
  { "title": "Monitor Events", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 } },
  {
   "title": "$MonitorName Event Count",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 4 },
   "repeat": "MonitorName",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "zm_monitor_event_count{name=\"$MonitorName\"}"
    }
   ]
  },
  { "title": "Monitor Function", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "$MonitorName Function",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 8 },
   "repeat": "MonitorName",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "zm_monitor_function{name=\"$MonitorName\"} == 1",
     "legendFormat": "{{zm_monitor_function}}"
    }
   ]
  },
  { "title": "Monitors", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "Monitor Enabled",
   "type": "state-timeline",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
   "targets": [
    { "expr": "zm_monitor_enabled", "legendFormat": "{{name}}" }
   ]
  },
  {
   "title": "Monitor Connected",
   "type": "state-timeline",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
   "targets": [
    { "expr": "zm_monitor_connected", "legendFormat": "{{name}}" }
   ]
  },
  {
   "title": "Monitor Events Per Hour",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "increase(zm_monitor_event_count[1h])",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Monitor Analysis FPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
   "targets": [
    { "expr": "zm_monitor_analysis_fps", "legendFormat": "{{name}}" }
   ]
  },
  {
   "title": "Monitor Capture FPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
   "targets": [
    { "expr": "zm_monitor_capture_fps", "legendFormat": "{{name}}" }
   ]
  },
  {
   "title": "Monitor Capture Bandwidth",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "zm_monitor_capture_bandwidth_bytes_per_second",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Monitor Action",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "zm_monitor_mmap_action", "legendFormat": "{{name}}" }
   ]
  },
  {
   "title": "Monitor Image Size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "zm_monitor_mmap_imagesize", "legendFormat": "{{name}}" }
   ]
  },
  {
   "title": "Monitor Last Frame Score",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "zm_monitor_mmap_last_frame_score",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Monitor Heartbeat Age",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "zm_monitor_mmap_heartbeat_time_age_seconds",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Monitor Last Read Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "zm_monitor_mmap_last_read_time_age_seconds",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Monitor Last Write Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "zm_monitor_mmap_last_write_time_age_seconds",
     "legendFormat": "{{name}}"
    }
   ]
  }
 ]
}